### PR TITLE
✨feat(password): detect password protected documents

### PR DESCRIPTION
**Pull request by jgoldhammer**
- previously opening password protected files resulted in a generic exception which did not allow to get the root cause
- now we handle opening documents with an interaction handler which gets triggered when a password is requested. With this mechanism it is possible to detect the case of opening password protected files and throw a specific exception.

Implementation note:
- The XInteractionHandler does not allow to throw checked exceptions and also unchecked exceptions will be ignored. ThreadLocals was the only way for me to implement it.

This should solve issue #233

### CODE REVIEW

**Comment by sbraconnier** [comment]
Wow.. this is wonderful work!! I'm on a cell phone right now so little tiny to review all the details but I'll prioritize this next week! Thank you so much!

**Comment by jgoldhammer** [comment]
> Wow.. this is wonderful work!! I'm on a cell phone right now so little tiny to review all the details but I'll prioritize this next week! Thank you so much!

Unfortunately freebsd tests are failing and I have no clue  why!

**Comment by sbraconnier** [comment]
FreeBsb is a great os but a PITA to integrate in unit tests. I lost so many hours of my life trying to get my tests succeed on freebsd to end with a working thread sleep I have no idea why the heck this sleep changed the tests results... don't do the same mistake!  Life is too valuable :). I won't reject this PR only because it fails on free bsd... great work!

**Comment by jgoldhammer** [comment]
I have to close this PR- please use https://github.com/sbraconnier/jodconverter/pull/256

**Pull request closed without merging**
