### PR TITLE
✨feat(password): detect password protected documents

### PR DESCRIPTION
**Pull request by jgoldhammer**
- previously opening password protected files resulted in a generic exception which did not allow to get the root cause
- now we handle opening documents with an interaction handler which gets triggered when a password is requested. With this mechanism it is possible to detect the case of opening password protected files and throw a specific exception.

Implementation note:
- The XInteractionHandler does not allow to throw checked exceptions and also unchecked exceptions will be ignored. ThreadLocals was the only way for me to implement it.

This should solve issue #233

### CODE REVIEW

**Comment by sbraconnier** [comment]
I'll review this on Wednesday (April 21).

**Review by sbraconnier — COMMENTED** [review]
Thanks for your work.

I would have prefer a solution with a configurable option that would have activate this "password protected handling" instead of making this handling the default behavior for all the conversions. I'll think about it and come back to you tommorow with my suggestion (it's 1 AM here!).

Thanks again!

**Comment by jgoldhammer** [comment]
Hi Simon,

Thanks for your review. I also thought about a specific exception, I will change it.

My thoughts to a possible configuration of this behaviour: In my eyes, a password protected document cannot be converted at all and possible users of the library always want to know the reason for a failing conversion. If this interactionhandler is not enabled by default for example, the user will only see that there is a nullpointer which can mean anything or nothing, so I guess users always want to have more specific information about the reason why a document was not able to be converted. 

Besides that how should we configure it? Passing a parameter through the converter interface or a system property? What is the default value?

Yes, this would be a breaking change that we throw a specific PasswordProtectionExpection in case of a password protected document instead of a nullpointer exception. As a user I would be happy to see this error by default and always- I do not know any reason why a user should deactivate this behaviour...

WDYT @sbraconnier ?

**Comment by jgoldhammer** [comment]
What do you think, Simon?

**Comment by sbraconnier** [comment]
Hi!! Sorry I'm so busy this week!!

So, I really think it would be better if this behavior was optional and that we could activate it throught an option. And that is because:

- We don't know the impact this behavior will have on all os with all the supported version of LibreOffice/OpenOffice/Portable LibreOffice/etc...etc...etc... By making this behavior an option you have to activate, anybody who wants this new feature will do it knowingly. I learned this the hard way with this project. By adding some "default" behavior I thought was great, I broke something on an OS I didn't even know exists!! 
- Some people may use (like myself at work) jodconverter knowing that the converted file will never be password protected (we produce the files ourselves that we have to convert according to the client requirements (pdf, docx, whatever). So, I would prefer not to have an handler that would do some extra work knowing that there will never be password protected file to convert!

**Comment by sbraconnier** [comment]
I'm not sure how we should configured it. Maybe an option that would add a load property to the LocalConverter? And then we could check this property (Let's say with a custom key like "JODConverter.handlePasswordProtection") on in the loadDocument implementation?

**Comment by Boomcka** [comment]
I disagree with this approval :
>     * Some people may use (like myself at work) jodconverter knowing that the converted file will never be password protected (we produce the files ourselves that we have to convert according to the client requirements (pdf, docx, whatever). So, I would prefer not to have an handler that woulHad do some extra work knowing that there will never be password protected file to convert!
How we can grantee what all files are not password protection? How can I distinguish between the situation the file is broken or password protected? On my mind it is wrong way to expect certain user behavior. Of course the easiest way is to write in the documentation that this project only for password free files =)

**Comment by sbraconnier** [comment]
I finally had time to work on this., I made some modifications in order to remove the thread safe stuff and the errorCode in the OfficeException class.

I thought I followed the GitHub instruction to merge this PR but it seems the PR is still there even if the master branch contains the PR. I must have skip a step... So I will juste close this PR.

Feel free to comment the modifications I made.

**Comment by sbraconnier** [comment]
By the way, I didn't made this behavior optional. So, your initial was the right way to go.

**Pull request closed without merging**
