### PR TITLE
Make 127.0.0.1 in socket connection configurable

### LINKED ISSUE #241: ExternalOfficeManager always connects sockets to 127.0.0.1
ExternalServiceManager uses hard coded connection to 127.0.0.1. In our environment with Docker, we need to be able to parameterize the host name as it used to be in older libraries.

### PR DESCRIPTION
**Pull request by nikowitt**
Pull request fo fix #241.

### CODE REVIEW

**Comment by sbraconnier** [comment]
Sorry for the delay and thanks for your contribution!

**Comment by nikowitt** [comment]
Great, thank you very much! As I really like to switch back to the master releases, do you know when you will create a new release?

**Comment by sbraconnier** [comment]
It will be within the next 2 weeks.

**Comment by nikowitt** [comment]
Nice, thank you :)

**Comment by chenbihao** [comment]
> 拉取请求修复 #241。

I wonder if you could help me with this?
#260 

I use my computer(win10), wanna connect the remote openOffice(vm ubuntu docker container)

```java
 manager = LocalOfficeManager.builder().install()
                .portNumbers(8100)
                .hostName("192.168.86.128")
                .taskExecutionTimeout(5 * 60 * 1000L)
                .taskQueueTimeout(1000 * 1000 * 60 * 24L)
                .maxTasksPerProcess(20)
                .build();
```
but it error:
```
org.jodconverter.core.office.OfficeException: Could not open document: tempfile_0.xlsx
	at org.jodconverter.local.task.AbstractLocalOfficeTask.loadDocument(AbstractLocalOfficeTask.java:126) ~[jodconverter-local-4.4.2.jar:4.4.2]
	at org.jodconverter.local.task.LocalConversionTask.execute(LocalConversionTask.java:117) ~[jodconverter-local-4.4.2.jar:4.4.2]
	at org.jodconverter.local.office.LocalOfficeManagerPoolEntry.doExecute(LocalOfficeManagerPoolEntry.java:120) [jodconverter-local-4.4.2.jar:4.4.2]
	at org.jodconverter.core.office.AbstractOfficeManagerPoolEntry.lambda$execute$0(AbstractOfficeManagerPoolEntry.java:80) [jodconverter-core-4.4.2.jar:4.4.2]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]
Caused by: com.sun.star.lang.IllegalArgumentException: URL seems to be an unsupported one.
```

I needs a little help.  QAQ

**Pull request merged**
