### PR TITLE
Migrate to swagger v3 / openapi - fixes #317

### LINKED ISSUE #317: With 4.4.3+ i get an exception missing classes for the DefaultDocumentFormatRegistry
I'am currently updating https://github.com/EugenMayer/officeconverter to the newest jodconvert version.

Coming from 4.3.0 i can upgrade to 4.4.2 without issues, 4.4.3+ though throw me an error on the integration test

https://github.com/EugenMayer/officeconverter/blob/main/src/test/java/de/kontextwork/converter/web/ConversionControllerTest.java#L39

```
  org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.jodconverter.core.document.DefaultDocumentFormatRegistry
      at app//de.kontextwork.converter.web.ConversionControllerTest.convertDotxWorks(ConversionControllerTest.java:75)
```

Anything unexpected changed with the Document Format Registry.

I checked the release notes https://github.com/sbraconnier/jodconverter/releases/tag/v4.4.3 and https://github.com/sbraconnier/jodconverter/releases/tag/v4.4.4 but did not find anything directly related.

Greatful for any help!

### PR DESCRIPTION
**Pull request by EugenMayer**
- upgrade spring boot to 2.7.6
- add smoke test for the application
- add openapi specs to the readme
- slightly reorder dependencies, added junit, openapi, swaggerv3 mockito

this also fixes #317

### CODE REVIEW

**Comment by EugenMayer** [comment]
@sbraconnier sorry for being as bold as this PR, hopefully i did not go to far out of the window.

The only global thing i did is updating to spring boot 2.7.6 (from 2.7.3), so that is the only thing that affects the "entire library".

All the bolder actions where local to the example "rest" project, and since i assume nobody uses that as a library or similar, i was bolder to change things.

The motivation was to get rid of swagger2, since it is deprecated. With #317 this already was troublesome. I upgraded to the newest / stable openapi variant with swaggerv3 annotations and migration the annotations accordingly.

I also added a smoke test to avoid us running into the same issue again.

If you want to me split those things up, let me know, but i hope this is "local" enough.

**Comment by EugenMayer** [comment]
Concerning the macos build issue, at least the case should be there https://formulae.brew.sh/cask/libreoffice and the mirror `https://download.documentfoundation.org/libreoffice/stable/7.4.3/mac/x86_64/LibreOffice_7.4.3_MacOS_x86-64.dmg` is up. So it might just be a glitch and needs a rerun.

**Comment by EugenMayer** [comment]
(retriggering the macos build fixed it, as expected)

**Comment by sbraconnier** [comment]
Wow. Thanks a lot for your contribution. This was on my todo list.

**Pull request merged**
